Repository Pinback-Team/pinback-client, pull requests merged in 2025-09, with the labels that each got.

#49 Feat(client): Time picker 구현
  apps/client/src/pages/onBoarding/OnBoarding.tsx
  apps/client/src/pages/onBoarding/components/.gitkeep
  apps/client/src/pages/onBoarding/components/timePicker/TimePicker.tsx
  apps/client/src/routes/router.tsx
  apps/client/src/routes/routesConfig.ts
  packages/design-system/components.json
  packages/design-system/package.json
  packages/design-system/src/components/badge/Badge.stories.tsx
  packages/design-system/src/components/button/Button.tsx
  packages/design-system/src/components/card/MyBookmarkCard.tsx
  packages/design-system/src/components/card/RemindCard.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/progress/Progress.tsx
  packages/design-system/src/components/switch/Switch.tsx
  packages/design-system/src/components/textarea/Textarea.tsx
  packages/design-system/src/components/toast/Toast.tsx
  packages/design-system/src/components/toast/hooks/uesFadeOut.tsx
  packages/design-system/src/components/wheelPicker/WheelPicker.tsx
  packages/design-system/tsconfig.json
  packages/design-system/vite.config.ts
  packages/tailwind-config/shared-styles.css
  pnpm-lock.yaml
Labels: feat

#65 Setting(project): axios, tanstack query 세팅
  apps/client/package.json
  apps/client/src/shared/apis/.gitkeep
  apps/client/src/shared/apis/axiosInstance.ts
  apps/client/src/shared/apis/query/getQueryClient.ts
  apps/client/src/shared/apis/query/queryClientOptions.ts
  apps/extension/package.json
  apps/extension/src/apis/axiosInstance.ts
  apps/extension/src/apis/query/getQueryClient.ts
  apps/extension/src/apis/query/queryClientOptions.ts
  pnpm-lock.yaml
Labels: setting

#64 Feat(extension): 익스텐션 페이지 레이아웃 및 북마크 저장
  apps/extension/manifest.json
  apps/extension/popup.html
  apps/extension/public/icon.png
  apps/extension/public/icon128.png
  apps/extension/src/App.tsx
  apps/extension/src/assets/logo.svg
  apps/extension/src/background.ts
  apps/extension/src/content.ts
  apps/extension/src/hooks/usePageMeta.ts
  apps/extension/src/hooks/useSaveBookmarks.ts
  apps/extension/src/popup.tsx
  apps/extension/src/utils/OGFetch.ts
  apps/extension/tsconfig.json
  apps/extension/vite.config.ts
  packages/design-system/src/components/dateTime/DateTime.tsx
  packages/design-system/src/components/dateTime/utils/FormatData.ts
  packages/design-system/src/components/dateTime/utils/ValidateData.ts
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/infobox/InfoBox.tsx
  packages/design-system/src/components/input/Input.stories.tsx
  packages/design-system/src/components/input/Input.tsx
  packages/design-system/src/components/popup/Popup.tsx
  packages/design-system/src/components/popup/PopupContainer.tsx
  packages/design-system/src/components/wheelPicker/WheelPicker.tsx
  packages/design-system/src/icons/iconNames.ts
  packages/design-system/src/icons/source/main_logo.svg
  packages/design-system/src/icons/source/tooltip_1.svg
  packages/design-system/src/icons/source/tooltip_2.svg
  packages/design-system/src/icons/source/tooltip_3.svg
  packages/design-system/src/icons/source/tooltip_4.svg
  packages/design-system/src/icons/source/tooltip_5.svg
Labels: feat

#82 Api(client): Dashboard article 전체 조회 API 연결
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/myBookmark/apis/axios.ts
  apps/client/src/pages/myBookmark/apis/queries.ts
  apps/client/src/pages/myBookmark/types/api.ts
  apps/client/src/pages/remind/Remind.tsx
  apps/client/src/pages/remind/apis/axios.ts
  apps/client/src/pages/remind/apis/queries.ts
  apps/client/src/pages/remind/types/api.ts
Labels: api

#86 Feat(onboarding): 온보딩 회원가입 api 연결
  apps/client/src/pages/onBoarding/components/funnel/AlarmBox.tsx
  apps/client/src/pages/onBoarding/components/funnel/MainCard.tsx
  apps/client/src/pages/onBoarding/utils/formatRemindTime.ts
  apps/client/src/shared/apis/axios.ts
  apps/client/src/shared/apis/queries.ts
Labels: api

#83 Feat(client): card edit delete
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/remind/Remind.tsx
  apps/client/src/shared/utils/anchorPosition.ts
  packages/design-system/src/components/card/Card.tsx
  packages/design-system/src/components/card/MyBookmarkCard.tsx
  packages/design-system/src/components/card/RemindCard.tsx
Labels: feat

#79 Api(client): category 수정 연결
  apps/client/src/shared/apis/axios.ts
  apps/client/src/shared/apis/queries.ts
  apps/client/src/shared/components/sidebar/PopupPortal.tsx
  apps/client/src/shared/components/sidebar/Sidebar.tsx
  packages/design-system/src/components/popup/Popup.tsx
Labels: api

#92 Api(client): DeleteCategory 연결
  apps/client/src/shared/apis/axios.ts
  apps/client/src/shared/apis/queries.ts
  apps/client/src/shared/components/sidebar/Sidebar.tsx
Labels: api

#96 Api(client): 아티클 읽음 상태 변경 API 연결
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/remind/Remind.tsx
  apps/client/src/shared/apis/axios.ts
  apps/client/src/shared/apis/queries.ts
  apps/client/src/shared/types/api.ts
  packages/design-system/src/components/card/BaseCard.tsx
  packages/design-system/src/components/card/MyBookmarkCard.tsx
  packages/design-system/src/components/card/RemindCard.tsx
Labels: api

#80 Api(extension): 익스텐션 api (수정,생성) 연결 및 페이지 구조 수정
  apps/extension/popup.html
  apps/extension/src/App.tsx
  apps/extension/src/apis/axios.ts
  apps/extension/src/apis/query/queries.ts
  apps/extension/src/hooks/useCategoryManager.ts
  apps/extension/src/hooks/usePageMeta.ts
  apps/extension/src/hooks/useSaveBookmarks.ts
  apps/extension/src/pages/DuplicatePop.tsx
  apps/extension/src/pages/MainPop.tsx
  apps/extension/src/types/types.ts
  apps/extension/src/utils/remindTimeFormat.ts
  apps/extension/tsconfig.json
  packages/design-system/src/components/dateTime/DateTime.stories.tsx
  packages/design-system/src/components/dateTime/DateTime.tsx
  packages/design-system/src/components/dateTime/utils/ValidateData.ts
  packages/design-system/src/components/dropdown/Dropdown.tsx
  packages/design-system/src/components/popup/PopupContainer.tsx
  packages/design-system/src/icons/iconNames.ts
  packages/design-system/src/icons/source/chippi_profile.svg
  packages/design-system/src/icons/source/dotori.svg
  packages/design-system/src/icons/source/logo.svg
  packages/design-system/src/icons/source/saved.svg
Labels: api

#97 Api(client): 아티클 수정 API 연결
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/myBookmark/apis/axios.ts
  apps/client/src/pages/myBookmark/apis/queries.ts
  apps/client/src/pages/remind/Remind.tsx
  apps/client/src/shared/apis/axios.ts
  apps/client/src/shared/apis/queries.ts
  apps/client/src/shared/components/cardEditModal/CardEditModal.tsx
  apps/client/src/shared/hooks/usePageMeta.ts
  apps/client/src/shared/types/api.ts
  apps/client/src/shared/utils/fetchOgData.ts
  apps/client/src/shared/utils/formatDateTime.ts
  apps/client/tsconfig.json
  packages/design-system/src/components/infobox/InfoBox.tsx
Labels: api

#98 Api(client): 북마크, 리마인드 페이지 article delete 연결
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/remind/Remind.tsx
  apps/client/src/shared/apis/axios.ts
  apps/client/src/shared/apis/queries.ts
Labels: api

#99 Feat(client&extension): 온보딩<->익스텐션 데이터 통신 작업
  apps/client/src/pages/onBoarding/components/funnel/MainCard.tsx
  apps/client/src/shared/apis/queries.ts
  apps/extension/manifest.json
  apps/extension/src/App.tsx
  apps/extension/src/apis/axiosInstance.ts
  apps/extension/src/background.ts
  apps/extension/src/content.ts
  apps/extension/src/hooks/useSaveBookmarks.ts
  apps/extension/src/pages/MainPop.tsx
Labels: feat

#110 Feat: 개발 QA 1차(정민 | 레벨페이지 수정)
  apps/client/src/pages/level/Level.tsx
  apps/client/src/pages/level/components/NextAcornTime.tsx
  apps/client/src/pages/level/hooks/useCountdown.ts
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/remind/Remind.tsx
  apps/client/src/shared/apis/queries.ts
  apps/client/src/shared/types/api.ts
  packages/design-system/src/icons/source/chippi_profile.svg
  packages/design-system/src/icons/source/tooltip_1.svg
  packages/design-system/src/icons/source/tooltip_2.svg
  packages/design-system/src/icons/source/tooltip_3.svg
  packages/design-system/src/icons/source/tooltip_4.svg
  packages/design-system/src/icons/source/tooltip_5.svg
Labels: refactor

#115 Feat(재림): 익스텐션, 온보딩 2차 QA
  apps/client/src/pages/onBoarding/components/funnel/AlarmBox.tsx
  apps/client/src/pages/onBoarding/components/funnel/MainCard.tsx
  apps/client/src/shared/utils/ValidateData.ts
  apps/extension/src/apis/axiosInstance.ts
  apps/extension/src/assets/extension_pop.svg
  apps/extension/src/assets/extension_thumb.svg
  apps/extension/src/background.ts
  apps/extension/src/hooks/useCategoryManager.ts
  apps/extension/src/pages/DuplicatePop.tsx
  apps/extension/src/pages/MainPop.tsx
  packages/design-system/src/components/dateTime/DateTime.tsx
  packages/design-system/src/components/dateTime/utils/FormatData.ts
  packages/design-system/src/components/dateTime/utils/ValidateData.ts
  packages/design-system/src/icons/iconNames.ts
  packages/design-system/src/icons/source/chippi_profile.svg
  packages/design-system/src/icons/source/extension_pop.svg
  packages/design-system/src/icons/source/extension_thumb.svg
  packages/design-system/src/icons/source/ic_extension.svg
  packages/design-system/src/icons/source/main_header_logo.svg
  packages/design-system/src/icons/source/tooltip_1.svg
  packages/design-system/src/icons/source/tooltip_2.svg
  packages/design-system/src/icons/source/tooltip_3.svg
  packages/design-system/src/icons/source/tooltip_4.svg
  packages/design-system/src/icons/source/tooltip_5.svg
Labels: feat

#113 Feat: 개발 QA 1차(정민 | 카테고리 팝업 수정)
  apps/client/src/shared/components/optionsMenuButton/OptionsMenuButton.tsx
  apps/client/src/shared/components/sidebar/PopupPortal.tsx
  apps/client/src/shared/components/sidebar/Sidebar.tsx
Labels: fix

#118 Feat: 개발 QA 1차(정민 | 수정하기 모달창 데이트타임 포맷)
  apps/client/src/shared/components/cardEditModal/CardEditModal.tsx
  apps/client/src/shared/utils/datetime.ts
Labels: fix

#125 Feat: 개발 QA 1차(정민 | 레벨페이지 이미지 재저장)
  packages/design-system/src/icons/source/chippi_profile.svg
  packages/design-system/src/icons/source/tooltip_1.svg
  packages/design-system/src/icons/source/tooltip_2.svg
  packages/design-system/src/icons/source/tooltip_3.svg
  packages/design-system/src/icons/source/tooltip_4.svg
  packages/design-system/src/icons/source/tooltip_5.svg
Labels: fix

#123 Feat: 개발 QA 1차(정민 | 랜딩페이지 디테일 수정)
  apps/client/index.html
  apps/client/public/chippi_extension_popup.svg
  apps/landing/index.html
  apps/landing/public/chippi_extension_popup.svg
  apps/landing/public/vite.svg
  apps/landing/src/App.tsx
  apps/landing/src/components/Header.tsx
  apps/landing/src/components/HeroSection.tsx
Labels: fix

#121 Feat: 개발 QA 1차(정민 | 삭제하기 모달 추가)
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/remind/Remind.tsx
Labels: fix

#130 sp1 1차 QA 반영 (대시보드-기능 관련)
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/remind/Remind.tsx
  apps/client/src/shared/components/cardEditModal/CardEditModal.tsx
  packages/design-system/src/components/card/MyBookmarkCard.tsx
  packages/design-system/src/components/card/RemindCard.tsx
Labels: fix

#134 Feat(client): 개발 QA 1차(사이드바 카테고리 이모지 카운트 수정)
  apps/client/src/shared/components/sidebar/PopupPortal.tsx
  apps/client/src/shared/utils/grapheme.ts
Labels: fix

#141 Fix(client): category edit query string sync
  apps/client/src/shared/components/sidebar/Sidebar.tsx
Labels: fix

#145 Fix(client): category article api schema 수정 & chip 컴포넌트 적용
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/myBookmark/apis/axios.ts
  apps/client/src/pages/myBookmark/apis/queries.ts
  apps/client/src/pages/myBookmark/components/fetchCard/FetchCard.tsx
  apps/client/src/pages/remind/components/fetchCard/FetchCard.tsx
  packages/design-system/src/components/card/Card.tsx
  packages/design-system/src/components/card/MyBookmarkCard.tsx
  packages/design-system/src/components/card/RemindCard.tsx
  packages/design-system/src/components/chip/Chip.tsx
Labels: fix

#152 Fix(landing client): 중복된 코드 수정
  apps/client/index.html
  apps/landing/index.html
Labels: feat

#163 Fix(client): FCM 연동 설정 로직 수정
  apps/client/public/firebase-config.js
  apps/client/public/firebase-messaging-sw.js
  apps/client/src/pages/onBoarding/components/funnel/MainCard.tsx
  apps/client/vercel.json
Labels: feat, fix

#158 Feat(client): article intersection observer로 infinite scroll 구현
  apps/client/src/pages/myBookmark/MyBookmark.tsx
  apps/client/src/pages/myBookmark/apis/queries.ts
  apps/client/src/pages/remind/Remind.tsx
  apps/client/src/pages/remind/apis/queries.ts
  apps/client/src/shared/hooks/.gitkeep
  apps/client/src/shared/hooks/useInfiniteScroll.ts
Labels: feat
