Repository Pinback-Team/pinback-client, pull requests merged in 2025-07, with the labels that each got.

#16 Docs(project): README ver 1.0 작성
  README.md
Labels: 📃 Docs, 진혁

#14 Setting(project): router 설정
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/main.tsx
  apps/client/src/pages/home/home.tsx
  apps/client/src/routes/router.tsx
  apps/client/src/routes/routesConfig.ts
  apps/landing/package.json
  apps/landing/src/App.tsx
  apps/landing/src/main.tsx
  apps/landing/src/pages/home/home.tsx
  apps/landing/src/routes/router.tsx
  apps/landing/src/routes/routesConfig.ts
  pnpm-lock.yaml
Labels: ⚙️ Setting, 정민

#10 Setting(project): tailwind css setup
  apps/client/package.json
  apps/client/src/App.tsx
  apps/client/src/index.css
  apps/client/vite.config.ts
  apps/landing/package.json
  apps/landing/src/App.tsx
  apps/landing/src/index.css
  apps/landing/vite.config.ts
  pnpm-lock.yaml
Labels: ⚙️ Setting, 정민

#12 Setting(project): axios query setup
  apps/client/.gitignore
  apps/client/package.json
  apps/client/src/main.tsx
  apps/client/src/shared/apis/axiosInstance.ts
  apps/client/src/shared/utils/queryClient.ts
  apps/landing/.gitignore
  apps/landing/package.json
  apps/landing/src/main.tsx
  apps/landing/src/shared/apis/axiosInstance.ts
  apps/landing/src/shared/utils/queryClient.ts
  pnpm-lock.yaml
Labels: ⚙️ Setting, 정민

#9 setting(project): 깃 액션 세팅 및 vercel 배포
  .github/labeler.yml
  .github/workflows/auto-label.yml
  vercel.json
Labels: ⚙️ Setting, 재림, config, needs-review

#25 Setting(design-system): shadcn-ui default setting
  packages/design-system/components.json
  packages/design-system/package.json
  packages/design-system/src/styles/color.css
  packages/design-system/tsconfig.json
  pnpm-lock.yaml
Labels: ⚙️ Setting, 진혁

#28 setting : extension 확장자 프로그램 초기 세팅
  apps/extension/ .babelrc
  apps/extension/.gitignore
  apps/extension/.gitkeep
  apps/extension/index.html
  apps/extension/package-lock.json
  apps/extension/package.json
  apps/extension/postcss.config.cjs
  apps/extension/public/icon128.png
  apps/extension/public/icon16.png
  apps/extension/public/icon48.png
  apps/extension/public/manifest.json
  apps/extension/src/App.css
  apps/extension/src/App.tsx
  apps/extension/src/background.ts
  apps/extension/src/content.ts
  apps/extension/src/custom.d.ts
  apps/extension/src/logo.png
  apps/extension/src/popup.tsx
  apps/extension/tailwind.config.ts
  apps/extension/tsconfig.json
  apps/extension/vite.config.ts
  packages/design-system/src/styles/font.css
  pnpm-lock.yaml
Labels: ⚙️ Setting, 재림, frontend

#39 Feature(extension): 토글 스위치 제작
  apps/client/package.json
  apps/extension/package.json
  apps/extension/src/components/toggleButton/ToggleButton.tsx
  apps/extension/tsconfig.json
  packages/design-system/package.json
  pnpm-lock.yaml
Labels: 🛠️ Feature, 정민

#32 Feature(extension): 텍스트 필드 팝업 구현
  apps/extension/package.json
  apps/extension/src/App.tsx
  apps/extension/src/components/textfieldPopup/TextfieldPopup.tsx
  apps/extension/vite.config.ts
  packages/design-system/src/icons/iconNames.ts
  packages/design-system/src/icons/source/close-button.svg
  pnpm-lock.yaml
Labels: 🛠️ Feature, 정민

#57 Feature(design-system): dot-indicator 공통 컴포넌트 구현
  packages/design-system/src/components/dotIndicator/DotIndicator.tsx
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/input/Input.tsx
Labels: 🛠️ Feature, 진혁

#60 Feature(client): onBoarding carousel및 story step 컴포넌트 구현
  apps/client/src/assets/onBoarding/storyStep1.svg
  apps/client/src/assets/onBoarding/storyStep2.svg
  apps/client/src/assets/onBoarding/storyStep3.svg
  apps/client/src/pages/onBoarding/OnBoarding.tsx
  apps/client/src/pages/onBoarding/components/.gitkeep
  apps/client/src/pages/onBoarding/components/Carousel.tsx
  apps/client/src/pages/onBoarding/components/StoryStep.tsx
  apps/client/src/pages/onBoarding/components/TimeSelectStep.tsx
  apps/client/src/pages/onBoarding/constants/storyStep.ts
  apps/client/src/pages/onBoarding/types/index.ts
  apps/client/src/shared/hooks/useFunnel.tsx
Labels: 🛠️ Feature, 진혁

#36 Feature(extension): 카테고리 드롭다운 컴포넌트 구현
  apps/extension/package.json
  apps/extension/src/components/category_dropdown/CategoryDropDown.tsx
  apps/extension/vite.config.ts
  packages/design-system/src/icons/iconNames.ts
  packages/design-system/src/icons/scripts/generate-icon-list.ts
  packages/design-system/src/icons/source/default_order.svg
  packages/design-system/src/icons/source/down_icon.svg
  packages/design-system/src/icons/source/plus_icon.svg
  packages/design-system/src/icons/source/white_order.svg
  pnpm-lock.yaml
Labels: 🛠️ Feature, 재림

#65 Refactor(client): 파일 구조 변경 및 디자인 통일
  apps/client/src/pages/dashboard/components/BookmarkCategory.tsx
  apps/client/src/pages/dashboard/components/DailyReminderSection.tsx
  apps/client/src/pages/dashboard/components/SectionTitle.tsx
  apps/client/src/pages/dashboard/components/features/BookmarkCategory.tsx
  apps/client/src/pages/dashboard/components/features/LevelInfoItem.tsx
  apps/client/src/pages/dashboard/components/features/SectionContent.tsx
  apps/client/src/pages/dashboard/components/features/SectionTitle.tsx
  apps/client/src/pages/dashboard/components/features/Timer.tsx
  apps/client/src/pages/dashboard/components/features/index.ts
  apps/client/src/pages/dashboard/components/index.ts
  apps/client/src/pages/dashboard/components/sections/BookmarkSection.tsx
  apps/client/src/pages/dashboard/components/sections/DailyReminderSection.tsx
  apps/client/src/pages/dashboard/components/sections/LevelInfoSection.tsx
  apps/client/src/pages/dashboard/components/sections/TestSection.tsx
  apps/client/src/pages/dashboard/components/sections/index.ts
  apps/client/src/pages/dashboard/components/ui/buttons/AllViewButton.tsx
  apps/client/src/pages/dashboard/components/ui/cards/BookmarkCard.tsx
  apps/client/src/pages/dashboard/components/ui/cards/DailyReminderCard.tsx
  apps/client/src/pages/dashboard/components/ui/cards/Thumbnail.tsx
  apps/client/src/pages/dashboard/components/ui/feedback/Modal.tsx
  apps/client/src/pages/dashboard/components/ui/feedback/Tooltip.tsx
  apps/client/src/pages/dashboard/components/ui/modals/LevelInfoModal.tsx
  apps/client/src/pages/dashboard/constants/cardSizes.ts
  apps/client/src/pages/dashboard/constants/index.ts
  apps/client/src/pages/dashboard/constants/levelData.ts
  apps/client/src/pages/dashboard/constants/tooltipMessages.ts
  apps/client/src/pages/dashboard/dashboard.tsx
  apps/client/src/pages/dashboard/hooks/useDashboard.ts
  apps/client/src/pages/dashboard/mockData.ts
  apps/client/src/pages/notFound.tsx
  apps/client/src/routes/router.tsx
  apps/client/src/shared/components/errorBoundary.tsx
  apps/client/src/shared/components/features/LevelInfoSection.tsx
  apps/client/src/shared/components/features/index.ts
  apps/client/src/shared/components/index.ts
  apps/client/src/shared/components/ui/display/EmptyState.tsx
  apps/client/src/shared/components/ui/display/EmptyStatePresets.ts
  apps/client/src/shared/components/ui/display/ReusableEmptyState.tsx
  apps/client/src/shared/components/ui/feedback/Tooltip.tsx
  apps/client/src/shared/components/ui/index.ts
  apps/client/src/shared/components/ui/layout/Header.tsx
  apps/client/src/shared/index.ts
  apps/client/src/shared/types/components.ts
  apps/client/src/shared/utils/cn.ts
  apps/client/src/shared/utils/styleUtils.ts
  apps/client/src/vite-env.d.ts
  apps/client/tsconfig.json
Labels: 🪄 Refactor, 서희

#90 Feature(client): design FCM token management & messaging architecture
  apps/client/package.json
  apps/client/public/firebase-config.js
  apps/client/public/firebase-messaging-sw.js
  apps/client/public/firebase_sdk/firebase-app-compat.js
  apps/client/public/firebase_sdk/firebase-messaging-compat.js
  apps/client/public/vite.svg
  apps/client/src/firebase-config.ts
  apps/client/src/pages/onBoarding/OnBoarding.tsx
  apps/client/src/pages/onBoarding/components/WelcomeStep.tsx
  apps/client/src/shared/utils/registerServiceWorker.ts
  apps/client/tsconfig.json
  apps/extension/public/manifest.json
  apps/extension/src/background.js
  pnpm-lock.yaml
Labels: 🛠️ Feature, 진혁

#89 Feature(client): 온보딩 ui 퍼블리싱
  apps/client/src/pages/onBoarding/OnBoarding.tsx
  apps/client/src/pages/onBoarding/components/Carousel.tsx
  apps/client/src/pages/onBoarding/components/MacUserNoticeStep.tsx
  apps/client/src/pages/onBoarding/components/OnboardingNavButton.tsx
  apps/client/src/pages/onBoarding/components/OnboardingTimePicker.tsx
  apps/client/src/pages/onBoarding/components/StoryStep.tsx
  apps/client/src/pages/onBoarding/components/TimeSelectStep.tsx
  apps/client/src/pages/onBoarding/components/WelcomeStep.tsx
  apps/client/src/pages/onBoarding/utils/formatSelectedTime.ts
  apps/client/src/shared/utils/registerServiceWorker.ts
  apps/client/src/vite-env.d.ts
  packages/design-system/package.json
  packages/design-system/src/components/index.ts
  packages/design-system/src/components/wheel-picker.tsx
  packages/design-system/src/icons/iconNames.ts
  packages/design-system/src/icons/source/ic_arrow_right.svg
  pnpm-lock.yaml
Labels: 🛠️ Feature, 정민

#93 Setting(extension): 익스텐션 쪽 API 세팅 및 client랑 데이터 연결 작업
  apps/client/src/pages/dashboard/dashboard.tsx
  apps/client/src/shared/utils/sendToken.ts
  apps/extension/public/manifest.json
  apps/extension/src/api/axiosInstance.ts
  apps/extension/src/background.js
  apps/extension/src/background.ts
  apps/extension/src/components/modalPop/ModalPop.tsx
  apps/extension/src/content.ts
  apps/extension/vite.config.ts
  pnpm-lock.yaml
Labels: ⚙️ Setting, 🛠️ Feature, 재림, frontend

#113 Feature(onboarding): story 변경사항 반영
  apps/client/src/assets/onBoarding/storyStep1.svg
  apps/client/src/assets/onBoarding/storyStep2.svg
  apps/client/src/assets/onBoarding/storyStep3.svg
  apps/client/src/pages/onBoarding/OnBoarding.tsx
  apps/client/src/pages/onBoarding/components/OnboardingTimePicker.tsx
  apps/client/src/pages/onBoarding/components/StoryStep.tsx
  apps/client/src/pages/onBoarding/constants/storyStep.ts
  apps/client/src/shared/components/ui/layout/Header.tsx
  packages/design-system/src/icons/iconNames.ts
Labels: 🛠️ Feature, 정민

#98 Feature(landing): UI 구현과 로띠 적용
  apps/client/src/assets/react.svg
  apps/landing/package.json
  apps/landing/src/assets/brand/logo.svg
  apps/landing/src/assets/lottie/dotorifalling.json
  apps/landing/src/assets/lottie/dotorifalling_top.json
  apps/landing/src/assets/lottie/lightbulb_chippi_final.json
  apps/landing/src/assets/lottie/note_lottie.json
  apps/landing/src/assets/lottie/progressbar_final.json
  apps/landing/src/pages/FeatureBookmarkSection.tsx
  apps/landing/src/pages/FeatureReminderSection.tsx
  apps/landing/src/pages/FeatureRewardSection.tsx
  apps/landing/src/pages/FinalCTASection.tsx
  apps/landing/src/pages/HeroSection.tsx
  apps/landing/src/pages/home/home.tsx
  apps/landing/src/shared/components/Button.tsx
  apps/landing/src/shared/components/layout/Header.tsx
  packages/design-system/src/icons/iconNames.ts
  packages/design-system/src/icons/source/dotori.svg
  packages/design-system/src/icons/source/ic_arrow_down_white.svg
  pnpm-lock.yaml
Labels: 🛠️ Feature, 정민

#114 Api (extension): 익스텐션 팝업 수정/삭제/생성 Edit 기능 API 연결
  apps/extension/src/api/axios.ts
  apps/extension/src/api/axiosInstance.ts
  apps/extension/src/api/queries.ts
  apps/extension/src/background.ts
  apps/extension/src/components/modalPop/ModalPop.tsx
  apps/extension/src/content.ts
  packages/design-system/src/components/category_dropdown/CategoryDropDown.tsx
  packages/design-system/src/components/textfieldPopup/TextfieldPopup.tsx
  packages/design-system/src/components/timePicker/TimePicker.tsx
  pnpm-lock.yaml
Labels: 🛠️ Feature, 재림, frontend

#119 Refactor: 개발 2차 QA 작업
  apps/client/src/pages/dashboard/apis/axios/category.ts
  apps/client/src/pages/dashboard/apis/query/category.ts
  apps/client/src/shared/components/ui/modalPop/ModalPop.tsx
  apps/extension/src/components/modalPop/ModalPop.tsx
  packages/design-system/src/components/category_dropdown/CategoryDropDown.tsx
Labels: 🛠️ Feature, 🪄 Refactor, 재림, frontend
